// Package interceptor provides typed, type-safe interceptors for config
// lifecycle operations. Unlike generic hooks, each interceptor has full
// compile-time type safety with dedicated request/response types per
// operation (Set, Delete, Reload, Bind, Close).
package interceptor

import (
	"context"

	"github.com/os-gomod/config/v2/internal/domain/event"
	"github.com/os-gomod/config/v2/internal/domain/value"
)

// ---------------------------------------------------------------------------
// Set Interceptor
// ---------------------------------------------------------------------------

// SetRequest represents a set operation request.
type SetRequest struct {
	Key   string
	Value any
}

// SetResponse represents the result of a set operation.
type SetResponse struct {
	Key      string
	OldValue value.Value
	NewValue value.Value
	Created  bool // true if the key did not exist before
}

// SetInterceptor intercepts set operations with full type safety.
// Implement BeforeSet to validate or transform the request before execution.
// Implement AfterSet to react to the result (e.g., notify watchers).
type SetInterceptor interface {
	BeforeSet(ctx context.Context, req *SetRequest) error
	AfterSet(ctx context.Context, req *SetRequest, res *SetResponse) error
}

// ---------------------------------------------------------------------------
// Delete Interceptor
// ---------------------------------------------------------------------------

// DeleteRequest represents a delete operation request.
type DeleteRequest struct {
	Key string
}

// DeleteResponse represents the result of a delete operation.
type DeleteResponse struct {
	Key      string
	OldValue value.Value
	Found    bool // true if the key existed and was deleted
}

// DeleteInterceptor intercepts delete operations with full type safety.
type DeleteInterceptor interface {
	BeforeDelete(ctx context.Context, req *DeleteRequest) error
	AfterDelete(ctx context.Context, req *DeleteRequest, res *DeleteResponse) error
}

// ---------------------------------------------------------------------------
// Reload Interceptor
// ---------------------------------------------------------------------------

// ReloadRequest represents a reload operation request.
type ReloadRequest struct {
	LayerNames []string // empty means reload all layers
}

// LayerError pairs a layer name with its reload error.
type LayerError struct {
	Layer string
	Err   error
}

// ReloadResponse represents the result of a reload operation.
type ReloadResponse struct {
	Events    []event.Event // events generated by the reload
	LayerErrs []LayerError  // per-layer errors (non-fatal)
	Changed   bool          // true if any config values actually changed
}

// ReloadInterceptor intercepts reload operations with full type safety.
type ReloadInterceptor interface {
	BeforeReload(ctx context.Context, req *ReloadRequest) error
	AfterReload(ctx context.Context, req *ReloadRequest, res *ReloadResponse) error
}

// ---------------------------------------------------------------------------
// Bind Interceptor
// ---------------------------------------------------------------------------

// BindRequest represents a bind operation request.
type BindRequest struct {
	Target any // pointer to the target struct or map to populate
}

// BindResponse represents the result of a bind operation.
type BindResponse struct {
	Target any      // the populated target (same pointer as request)
	Keys   []string // keys that were bound
}

// BindInterceptor intercepts bind operations with full type safety.
type BindInterceptor interface {
	BeforeBind(ctx context.Context, req *BindRequest) error
	AfterBind(ctx context.Context, req *BindRequest, res *BindResponse) error
}

// ---------------------------------------------------------------------------
// Close Interceptor
// ---------------------------------------------------------------------------

// CloseRequest represents a close operation request.
type CloseRequest struct{}

// CloseResponse represents the result of a close operation.
type CloseResponse struct{}

// CloseInterceptor intercepts close operations with full type safety.
type CloseInterceptor interface {
	BeforeClose(ctx context.Context, req *CloseRequest) error
	AfterClose(ctx context.Context, req *CloseRequest, res *CloseResponse) error
}
